# Generated by Django 5.2.6 on 2025-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_chatsession_id_alter_chatsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
