# Generated by Django 5.2.6 on 2025-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='cloudinary_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
